mkdir d:\music\1-new\
mkdir d:\music\2-score-games\
mkdir d:\music\3-score-films\
mkdir d:\music\4-ambient\
mkdir d:\music\5-8bit\
mkdir d:\music\6-electro\
mkdir d:\music\7-rap\
mkdir d:\music\8-random\
mkdir d:\music\9-ROCK\
